### ISSUE TITLE
Question: dynamic icon class?

### ISSUE THREAD

**Issue by seagullmouse** [rmja/aurelia-fontawesome-loader#1]
In my use case I have a dynamic icon class within a component.

E.g. my variable is called `iconClass` and is bound to my component.

This doesn't quite fit into any of the examples you have shown

```<font-awesome-icon icon.bind="iconClass"></font-awesome-icon>```
Doesn't run the & fontawesome binding.

```<font-awesome-icon icon.bind="iconClass & fontawesome"></font-awesome-icon>```
Doesn't require the icon class.
Your example states "Require the icon manually and use it with the fontawesome binding behavior". Is it possible to do that dynamically, i.e. based on the bound variable iconClass?

I'm probably overlooking a simple a solution so appreciate your help!

**Comment by rmja** [comment]
In that case you should assign the actual icon to the iconClass in the view model, e.g.

```
export class MyComponent {
  iconClass = faClock;
}
```

Alternatively, use a value converter if you need some kind of string-to-icon logic, e.g.

```
export class MyComponent {
  type = "something"
}

const typeMap = {
  "something": faClock
};

export TypeToIconValueConverter {
  toView(type) {
    return typeMap[type];
  }
}
```

(Note that you can use the value converter directly in the corresponding view without the `<require from="..."></requre>`) Then, in the view, use: `<font-awesome-icon icon.bind="type | typeToIcon"></font-awesome-icon>`.

**Comment by seagullmouse** [comment]
Thanks for your reply. I want to dynamically deal with any FA icon. If I
need to load them all into a type map then I think that defeats the purpose
of the webpack loader. Ie that type map would load all the icons into
memory? feels like there should be a solution here but maybe I'm missing
something. Cheers

**Comment by rmja** [comment]
The thing is that the loader needs to resolve the dependencies at compile
time.

tir. 16. jul. 2019 16.37 skrev Matthew Hersee <notifications@github.com>:

> Thanks for your reply. I want to dynamically deal with any FA icon. If I
> need to load them all into a type map then I think that defeats the purpose
> of the webpack loader. Ie that type map would load all the icons into
> memory? feels like there should be a solution here but maybe I'm missing
> something. Cheers
>
>
>
> On Tue, 16 Jul 2019 at 12:58, Rasmus Melchior Jacobsen <

**Comment by seagullmouse** [comment]
Yeah - I think best bet is to avoid the loader then and just stick them in
a map as you suggested.

Thanks again!

**Comment by rmja** [comment]
@seagullmouse I am closing this as I think the question is answered. Let me know if you need me to comment further on this.
