### ISSUE TITLE
Why do only brand icons require a 'fab' prefix but regular do not require 'far'?

### ISSUE THREAD

**Issue by lebolo** [rmja/aurelia-fontawesome-loader#2]
I'm using Aurelia w/ Webpack and have set up aurelia-fontawesome-loader and aurelia-fontawesome. Everything is working, but was curious why some icons required a prefix, others required a lack of prefix, and some are optional.

For example, the commented out elements give errors because of prefixes.

```html
<!--<font-awesome-icon icon="android"></font-awesome-icon>-->
<font-awesome-icon icon="grin-tongue-wink"></font-awesome-icon>
<font-awesome-icon icon="globe"></font-awesome-icon>

<font-awesome-icon icon.bind="['fab', 'android']"></font-awesome-icon>
<!--<font-awesome-icon icon.bind="['far', 'grin-tongue-wink']"></font-awesome-icon>-->
<font-awesome-icon icon.bind="['fas', 'globe']"></font-awesome-icon>
```

**Comment by rmja** [comment]
This comes from the https://github.com/pinterweb/aurelia-fontawesome and has nothing to do with the loader

**Comment by lebolo** [comment]
Oh okay, thanks! I'll move the issue over there.
