### ISSUE TITLE
does not work with html-loader 1.0.0

### ISSUE THREAD

**Issue by tmueller** [rmja/aurelia-fontawesome-loader#9]
Hi rmja,

thanks for such a nice package. 

When trying to upgrade to `html-loader` 1.0.0 `aurelia-fontawesome-loader` stopped working. It seems the problem is, that `html-loader/lib/attributesParser` is gone. Maybe you can have look into it? Thanks in advance :)

Greetings,
Thomas

**Comment by rmja** [comment]
Hi Thomas,

I will have a look at this when the projects that I use upgrade their dependencies. Hang on..

**Comment by rmja** [comment]
This is now fixed in v. 0.7. Please try it and let me know of any problems!
